apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: "{{repo_url}}/-/tree/{{revision}}"
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/pull_request_number: "{{pull_request_number}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression:
      event == "pull_request" && target_branch
      == "c10s"
  labels:
    appstudio.openshift.io/application: centos-bootc-c10s
    appstudio.openshift.io/component: centos-bootc-c10s
    pipelines.appstudio.openshift.io/type: build
  name: centos-bootc-c10s-on-pull-request
  namespace: centos-bootc-tenant
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: quay.io/redhat-user-workloads/centos-bootc-tenant/centos-bootc-c10s/centos-bootc-c10s:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: build-platforms
      value:
        - linux/amd64
        - linux/arm64
        - linux/ppc64le
        - linux/s390x
    - name: dockerfile
      value: Containerfile
    - name: path-context
      value: .
    - name: prefetch-input
      value: '[{"type": "rpm"}]'
    - name: workingdir-mount
      value: "/buildcontext"
    - name: privileged-nested
      value: "true"
  pipelineRef:
    resolver: git
    params:
      - name: serverURL
        value: https://gitlab.com
      - name: org
        value: redhat/rhel/containers
      - name: repo
        value: tekton-pipelines
      - name: pathInRepo
        value: .tekton/build-pipeline.yaml
      - name: revision
        value: main
      - name: scmType
        value: gitlab
      - name: token
        value: pipelines-as-code-secret
      - name: tokenKey
        value: password
  taskRunTemplate:
    serviceAccountName: build-pipeline-centos-bootc-c10s
    podTemplate:
      securityContext:
        privileged: true
        runAsUser: 0
      metadata:
        annotations:
          io.openshift.podman-fuse: ""
          io.kubernetes.cri-o.Devices: /dev/fuse
  taskRunSpecs:
    - pipelineTaskName: build-images
      stepSpecs:
        - name: sbom-syft-generate
          computeResources:
            limits:
              memory: 8Gi
    - pipelineTaskName: prefetch-dependencies
      stepSpecs:
        - name: prefetch-dependencies
          computeResources:
            limits:
              memory: 12Gi
  timeouts:
    pipeline: 4h0m0s
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
status: {}
